#include <iostream>
#include <string>
#include <list>
using namespace std;

/*
Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
*/ 

int main() {
  int total_sum, f2, f1, f0, p;

  total_sum = 0;
  f1 = 2;
  f0 = 1;
  p = 0;

  while(f1 < 4000000){
    if (f1 % 2 == 0) total_sum += f1; 
    p = f1 + f0;
    f0 = f1;
    f1 = p;
  }
  std::cout << total_sum << "\n";
  return total_sum;
}
